num_str = "0123456789"
print(num_str[2:6])
print(num_str[2:])
print(num_str[0:num_str.index("5")+1])
print(num_str[:])
print(num_str[::2])
print(num_str[1::2])
print(num_str[2:-1])
print(num_str[-2:])
print(num_str[::-1])
print(num_str[-1:])